### ISSUE TITLE
Getting "Creation Time (creation_time) is required" for all values of "creation_time"

### ISSUE THREAD

**Issue by surajpratap** [Abenity/abenity-ruby#1]
Hi there,

I use the example given in examples/sso_example.rb.

```
member_info = {
  "creation_time" => (DateTime.now).strftime('%FT%T%:z'),
  "salt" => rand(0..100000),
  "send_welcome_email" => "1",
  "client_user_id" => "1",
  "email" => "john.smith@acme.com",
  "firstname" => "John",
  "lastname" => "Smith",
  "address" => "2134 Main Street",
  "city" => "Irvine",
  "state" => "CA",
  "zip" => "92620",
  "country" => "US",
  "phone" => "234-234-2345",
  "position" => "NA"
}

results = ApiClient.sso_member(
  member_info,
  File.read("file_path_to_private_key")
)
```

with correct api keys and I'm always receiving 

"Creation Time (creation_time) is required".

Can you help me ? thanks

**Comment by markroland** [comment]
Hello Suraj,

We received the following github question regarding the abenity-ruby
package:

Hi there,

I use the example given in examples/sso_example.rb.

member_info = {
  "creation_time" => (DateTime.now).strftime('%FT%T%:z'),
  "salt" => rand(0..100000),
  "send_welcome_email" => "1",
  "client_user_id" => "1",
  "email" => "john.smith@acme.com",
  "firstname" => "John",
  "lastname" => "Smith",
  "address" => "2134 Main Street",
  "city" => "Irvine
<https://maps.google.com/?q=2134+Main+Street%22,%0D+%22city%22+%3D%3E+%22Irvine&entry=gmail&source=g>",
  "state" => "CA",
  "zip" => "92620",
  "country" => "US",
  "phone" => "234-234-2345 <(234)%20234-2345>",
  "position" => "NA"
}

results = ApiClient.sso_member(
  member_info,
  File.read("file_path_to_private_key")
)

with correct api keys and I'm always receiving

"Creation Time (creation_time) is required".

Can you help me ? thanks


Can you please verify your Abenity account for us so we can continue the
troubleshooting process?

Thanks

**Comment by surajpratap** [comment]
Hello @markroland ,

Its working for me now. But the weird this is if "creation_time" is first key in "member_info" hash, response always throws error = "Creation Time (creation_time) is required".

I added "creation_time" as the last in "member_info" and it works.

You might wanna check that :) 

Thanks

**Comment by markroland** [comment]
Thank you for your feedback. I’ll look into that.
